language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-es6' ]; then cd .. && eval "mv $currentfolder generator-es6" && cd generator-es6; fi

